export const installedFonts = ['Font Awesome 5 Free',
'hello honey - Personal Use',
'Birthstone',
'Qwigley',
'Ms Madi',
'Alex Brush',
'Parisienne',
'Courgette',
'Pacifico',
'Glory',
'Genos',
'Wendy One',
'Dongle',
'Manjari',
'Michroma',
'Blinker',
'Amaranth',
'Paytone One',
'Quicksand',
'Arial',
'Bahnschrift',
'Calibri',
'Cambria',
'Cambria Math',
'Candara',
'Comic Sans MS',
'Consolas',
'Constantia',
'Corbel',
'Courier New',
'Ebrima',
'Franklin Gothic',
'Gabriola',
'Gadugi',
'Georgia',
'Impact',
'Ink Free',
'Javanese Text',
'Leelawadee UI',
'Lucida Console',
'Lucida Sans Unicode',
'Malgun Gothic',
'Microsoft Himalaya',
'Microsoft JhengHei',
'Microsoft JhengHei UI',
'Microsoft New Tai Lue',
'Microsoft PhagsPa',
'Microsoft Sans Serif',
'Microsoft Tai Le',
'Microsoft YaHei',
'Microsoft YaHei UI',
'Microsoft Yi Baiti',
'MingLiU-ExtB',
'PMingLiU-ExtB',
'MingLiU_HKSCS-ExtB',
'Mongolian Baiti',
'MS Gothic',
'MS UI Gothic',
'MS PGothic',
'MV Boli',
'Myanmar Text',
'Nirmala UI',
'Palatino Linotype',
'Segoe Fluent Icons',
'Segoe MDL2 Assets',
'Segoe Print',
'Segoe Script',
'Segoe UI',
'Segoe UI Emoji',
'Segoe UI Historic',
'Segoe UI Symbol',
'Segoe UI Variable Small',
'Segoe UI Variable Text',
'Segoe UI Variable Display',
'SimSun',
'NSimSun',
'SimSun-ExtB',
'Sitka Small',
'Sitka Text',
'Sitka Subheading',
'Sitka Heading',
'Sitka Display',
'Sitka Banner',
'Sylfaen',
'Symbol',
'Tahoma',
'Times New Roman',
'Trebuchet MS',
'Verdana',
'Webdings',
'Wingdings',
'Yu Gothic',
'Yu Gothic UI',
'HoloLens MDL2 Assets',
'Agency FB',
'Akhbar MT',
'Algerian',
'Book Antiqua',
'AGA Arabesque',
'AGA Arabesque Desktop',
'Arial Rounded MT',
'Baskerville Old Face',
'Bauhaus 93',
'Bell MT',
'Bernard MT',
'Bold Art',
'Bodoni MT',
'Bodoni MT Poster',
'Bookman Old Style',
'Bradley Hand ITC',
'Britannic',
'Berlin Sans FB',
'Broadway',
'Brush Script MT',
'Bookshelf Symbol 7',
'Californian FB',
'Calisto MT',
'Castellar',
'Century Schoolbook',
'Centaur',
'Century',
'Chiller',
'Colonna MT',
'Cooper',
'Copperplate Gothic',
'Curlz MT',
'Diwani Bent',
'Diwani Letter',
'DecoType Thuluth',
'DecoType Naskh',
'DecoType Naskh Special',
'DecoType Naskh Variants',
'DecoType Naskh Extensions',
'DecoType Naskh Swashes',
'Dubai',
'Diwani Outline Shaded',
'Diwani Simple Outline 2',
'Diwani Simple Outline',
'Diwani Simple Striped',
'Elephant',
'Engravers MT',
'Eras ITC',
'Felix Titling',
'Forte',
'Franklin Gothic Book',
'Freestyle Script',
'French Script MT',
'Farsi Simple',
'Farsi Simple Outline',
'Footlight MT',
'Garamond',
'Gigi',
'Gill Sans MT',
'Gill Sans',
'Gloucester MT',
'Century Gothic',
'Goudy Old Style',
'Goudy Stout',
'Harlow Solid',
'Harrington',
'Haettenschweiler',
'High Tower Text',
'Imprint MT Shadow',
'Informal Roman',
'Blackadder ITC',
'Edwardian Script ITC',
'Kristen ITC',
'Italic Outline Art',
'Jokerman',
'Juice ITC',
'Kufi Outline',
'Kufi Outline Shaded',
'Monotype Koufi',
'Kunstler Script',
'Wide Latin',
'Lucida Bright',
'Lucida Calligraphy',
'Led Font',
'Lucida Fax',
'Lucida Handwriting',
'Lucida Sans',
'Lucida Sans Typewriter',
'Magneto',
'Maiandra GD',
'Matura MT Script Capitals',
'Mistral',
'Modern No. 20',
'Monotype Corsiva',
'MT Extra',
'Mudir MT',
'Niagara Engraved',
'Niagara Solid',
'OCR A',
'Old Antic',
'Old Antic Decorative',
'Old Antic Outline',
'Old English Text MT',
'Old Antic Outline Shaded',
'Onyx',
'MS Outlook',
'Palace Script MT',
'Papyrus',
'Parchment',
'Perpetua',
'Perpetua Titling MT',
'Playbill',
'Poor Richard',
'Pristina',
'PT Arch',
'PT Broken',
'PT Dusky',
'PT Heading',
'PT Mirror',
'PT Stars',
'PT Separated Baloon',
'Rage',
'Ravie',
'MS Reference Sans Serif',
'MS Reference Specialty',
'Rockwell',
'Script MT',
'Showcard Gothic',
'Snap ITC',
'Simple Jut Out',
'PT Simple Ruled',
'Simple Indust Outline',
'Simple Indust Shaded',
'Simple Outline Pat',
'Stencil',
'Tw Cen MT',
'Tempus Sans ITC',
'Viner Hand ITC',
'Vivaldi',
'Vladimir Script',
'Wingdings 2',
'Wingdings 3',
'Cascadia Code',
'Cascadia Mono',
'Marlett',
'Global User Interface',
'Global Monospace',
'Global Sans Serif',
'Global Serif',
]

